---
title: "Graphical Perception in a Pandemic: Log Scales, Exponential Growth, and the Importance of User Testing"
author: "Susan Vanderplas, Emily Robinson, Reka Howard"
date: "2024-03-29"
categories: talks
page-layout: full
title-block-banner: true

keywords: [NA, Talk]
format:
  html:
    code-copy: true
---
 
## Abstract
>  During COVID, people all over the world were consulting time-series charts on a daily basis and using these charts to make decisions. Discussions broke out among data visualization and scientific communication experts, debating the relative merits of log and linear scales, but there was relatively little research about how people perceive and use visualizations of exponential data, with linear or transformed scales. In this talk, I'll discuss the study we undertook to address the lack of research in this area, and how the results speak not only to the importance of additional graphical testing, but also to the trade offs between different levels of user engagement with visualizations.


## Location

    Epidemiology and Biostatistics Seminar, University of Illinois Chicago School of Public Health
    Event Type: Department Seminar
    Location: Chicago, IL (Online)

